# Generated by Django 6.0.4 on 2026-05-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagnosis_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='instruction',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.diagnosis'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
    ]
