# Generated by Django 6.0.4 on 2026-10-02 02:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_serviceapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service fee in INR. Use 0 for a free service.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='unpaid', max_length=12),
        ),
    ]
